# Generated by Django 3.1.3 on 2021-01-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='autor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(),
        ),
    ]
