# Generated by Django 3.1.3 on 2021-01-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210125_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='is_favorite',
            new_name='is_fav',
        ),
    ]
